apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  config.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 2048m
    taskmanager.numberOfTaskSlots: 2
    state.checkpoints.dir: s3://flink-savepoints/checkpoints/
    state.savepoints.dir: s3://flink-savepoints/savepoints/
    s3.endpoint: http://minio:9000
    s3.access-key: flinkadmin
    s3.secret-key: flinksecret
    s3.path.style.access: true
    s3.bucket.fs.impl: org.apache.flink.fs.s3hadoop.S3FileSystem
    env.java.opts.jobmanager: --add-opens=java.base/java.util=ALL-UNNAMED
    env.java.opts.taskmanager: --add-opens=java.base/java.util=ALL-UNNAMED
    env.java.opts: --add-opens=java.base/java.util=ALL-UNNAMED
    blob.server.port: 6124

