apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager-special
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
      type: special
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
        type: special
    spec:
      containers:
        - name: taskmanager
          image: iwita/flink:2.0
          args: ["taskmanager"]
          ports:
            - containerPort: 6121
            - containerPort: 6122
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
