# minio-deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  minio-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - --console-address
            - ":9001"
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: flinkadmin
            - name: MINIO_ROOT_PASSWORD
              value: flinksecret
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: storage
              mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30000
    - name: webui
      port: 9001
      targetPort: 9001
      nodePort: 30001
  selector:
    app: minio
